# Generated by Django 4.1.5 on 2024-01-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourspot",
            name="customer",
        ),
        migrations.AlterField(
            model_name="tourroute",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="backend.tourtype"
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reservation_data", models.TextField(blank=True, null=True)),
                (
                    "stripe_invoice_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("stripe_invoice", models.JSONField(blank=True, null=True)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backend.tour",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
                "managed": True,
            },
        ),
    ]
