# Generated by Django 4.1.5 on 2024-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_remove_tourspot_customer_alter_tourroute_tour_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("paid", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "checkout_session",
                "managed": True,
            },
        ),
    ]
