# Generated by Django 4.1.5 on 2024-01-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_checkoutsession_created_alter_checkoutsession_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="tour_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
