# Generated by Django 4.1.5 on 2024-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_checkoutsession_tour_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="total",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
