# Generated by Django 4.1.5 on 2024-01-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_tourtype_stripe_price_delete_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourtype",
            name="url",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
